services:
- docker

matrix:
  include:
    - env: BUILD_WHAT="evaluator"
#    - env: BUILD_WHAT="evaluator-noLD"
    - env: BUILD_WHAT="collector"
    - env: BUILD_WHAT="tidyrisk"

script:
  - if [ "$BUILD_WHAT" == "evaluator" ]; then make evaluator; fi
  - if [ "$BUILD_WHAT" == "evaluator-noLD" ]; then make evaluator-noLD; fi
  - if [ "$BUILD_WHAT" == "collector" ]; then make collector; fi
  - if [ "$BUILD_WHAT" == "tidyrisk" ]; then make tidyrisk; fi

after_success:
- docker rm -f evaluator collector
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- if [ "$BUILD_WHAT" == "evaluator" ]; then docker push tidyrisk/evaluator:latest; fi
- if [ "$BUILD_WHAT" == "evaluator-noLD" ]; then docker push tidyrisk/evaluator:noLD; fi
- if [ "$BUILD_WHAT" == "collector" ]; then docker push tidyrisk/collector:latest; fi
- if [ "$BUILD_WHAT" == "tidyrisk" ]; then docker push tidyrisk/tidyrisk:latest; fi

notifications:
  slack:
    secure: "lBu+n1YP9FaPTiSpDWZqBXDJF1yoTC77kw6VI26S0GO8RcyEMZZNYGsjiEoTu1SMxbJsvIRC6Jg3kiU7Vnoz9lV/Oj9Xp8oEmS5gL3AGiXq6L7yDxshOjAK0coa+aKIp6aP7xjOVZ9DqI7hCIJnelz9j/1APEwuPC+av4kBtcvnnz4oClKDn+LRpowIGJufZ1IplCXjIyb89WOvjwI7hA/0WO8m6B/W1vU9xxQfeVeaeCRc/29RrIIX1elXLdu1YF8q56DJsnspNSFP8RuXMXvID5IXIXFqfOKb6G5BhYjNvaeovP2MCd5XpO7LYWQzAttRRoKLYO+f3MFRNb4iLIcciGcGa6h/pus7YQud/dWfj94zFleWp0xezduFLgJFrQd8BQXQiSjPcWTA+okwQqCf9DEFJMgCcC1i5vEE2OYtExicG5+835v+n38MrQdRp144Xl0X+bqITWb2xjfCDk5SHdAXR9poNPp5356Pj1roptbO9byZX1afoxEZ1CF3T5F+H7PQjuFWq6P+uDQpOS6+0hVtRrU6ry6MmXUnfmcAA+kqlNmdVDE8VTyckIzxzg9Ac3X94uaNZrUxarPOIGOQhP0Gj+wrtc3wx/BdLspJMtLS/PHq560UiUU/glbGllEClBQl+sCqRs9hsJwC8znlXvSAy28bf4oHhiGyiqD8="
env:
  global:
# docker username
  - secure: "Rks7BuPVU1O9LDfn8GoaWuXSwfz4ywV+EVXhkiOnUXEpicyxepW7oXFa7EceBa/k/CybD3H729BOhqxpoWHJ6GkSgkj4k2noYfvciemJD65/gxHk6RsmrmALIHvCLmkSDaJDXQdWN1vtmwWTGScTBwf3RZe8qWQkKVMI0RBHR4VypWLP+fylaLHsD3YrMBeOJD56xqTMZU4O1w8a6AheprWy44zDmq1H6JmDu388PdF8nA+sIfCIow1b/NgyyssPaF0h/Xw7TJ/YjufXtlKMHl59nV+UfPZyJoV61Q04FONoWVt9ZNmTUwt1tf2KxTLQz/k9Wc5MPqsWEVGaAADhlKHQiUAXf4t4B9WNVmnHODIMDzfcxTEbn3xlTASYxjYkA8ydM/l+A1uoIx74M5tZofU0v7durXGPFDtram1IT+e7Do2Xa6RbEHNBzvwax/qxwTicr+cNS8gIXe78238w05vdQH9x3YhNOPatPAnrhx/uiWcL59RQ593wCqcQNjUfavfvZUtjCRdvImhnq5lB6gxFAHUWZD9BN8+j6Gmlzgfn/D0+6J2/koWepTCqprt0UdtiUeKyDp2EthO5uY/v8a0npgdGQ409NZ7f4/zOFzoxanaSx75DtvfbZj+Sy8FmM0//pNFT/gC0iw8sdWGWS/z348l3raHiILNpN6MhpGQ="
# docker password
  - secure: "R0iiyKgFY1t3JCvCNuW4wVoNru6j4mqnYMn/Dq9frX2uMPDSLijeJxD3IfMeJ48ppnz2Wst9aygpsXTuFgiYHwxxB829CN8O8HBtPIzR4sAlpVIQzVaOC4HWytjPEA/NFVyOEPP8sO23nRdR9l6/7Js2Lo8uzNWemr5vCYp+1BhWbjr1NFsNVo6vCbrOeKXyiznrsqMz4RbqD/pf23mKRk9anKeFPDl7AdSJaNd0mM9HYMSkuDF27KvOoNG5ClNUVG1Lcci2shBwcD30rA9aQoh1TswagYiAGYKWgGWM3/r/gjIX82Y1Xkg4xZRAMl8TkCZWGo33ywYH+mgqk9uT99P76vgsOZ0CqofxYaEK3x12okLxfRffLUZr1IrWEB9AEM/c+gU9M4PJOxDhuyjyFbELqkOTvkLqkuye9Fk0gWlEXfku9nzFNZ3aowqGDbgWfw2zMXZ56K3X/FqOwPCd49r/AzPQKfIUeOKPF4kMcZ1Ab2r/5NP1YeIhPpOvcbevk/Gu/GCMUHU0JmVu2QvG77O+RSpij7COdkdYIpI54QI1EgHFv3GMn2pmAL8uwRrr299VAT+WdiCzjo5WGIRYgCRkYMlJ4tnW45Vm6rGsjLeTSCRIo2wFMzdGp6d4OTjWg+15c/hjmRKUAdrhSC0mctx3GpDTOiTYLn+gDTaQCos="
# Github token
  - secure: "liJ+0EQMvFXktdBE/1/SHp91SkWxHusjlnnqWV3Ac9ztSDXGNnp60/fAIdtlkUOZ4fFFWY9tQ3TOYNY2+Ho7warf5W9Y83bsI9BiY/inSXbWonshzVndlhB0PiRhTB+3iSCUdmij7y0nW868jysHLvSYlS5fCYP7tLe5q5C299dsViMncxSfgookZ1BAZa/SitcuamWSrMNFAQP1wKVzF55NgTbaWhhSM6/ZSaqUkWLRZgLa1D4SQQZ1HLbJ+XsChY8WQmJjoCzJaqbNrKJFW2BqVZdb7T+eMA27O4IQLQ8SrJ8OWt8pDSdRksX3jaXEC34lQCMu8V6wfnAoJhHj4DyBnJnNUMHiYIEfOqhiDPKYPzsyr1CU+lz80br37VQcjuTEnrY7Ri3JCgSasIQiLqQXNdUWE1zB08Xii9RkP0fZ7mfnns4v8nbmx8a/QK/Gn/SCB6eDhsYgNp1h27pKQCYoeanVoPiydXtSlCUNXKySQnTyiew5IEyckmyTtHm9YHrCSxPyvHuT0Awnl25zLM5P5lWyahCil1TZjwC1XceOJFL867JB+FvCG/F+EHrtScK5Ftv9qXnLQyXmTzmRfW/cl06npOZpPhnFr5HZi3TxMkiPUtcebudqN/ZmdI/whMA8sRejN7E/TBRwQCvuXpmDTE4qOe9B0g99DJH4KIc="
# GITHUB_PAT 
  - secure: "bVrQ/c6/abuhP5SuDvTwdwo0O4mVx0oGBrBrNQOuN5gl9ZUTpKCmLCksedv40vyQI1ndzZhGGiluYd2NODOXcEjrJh7zfD3CtckI7n237NH41xvVEk/TKOzZCizx79t+3A2KsAkLAnd75ND+eMDRMEWVfocmI9hhXmANWomm8ZEoq+GAuplnLKzRYWthRlxjnYoB1xhFMX5LYLQ5pTw89Y2qSdbErLPNPXI/o9dIY6cG1oiLjx5gJShgt4kFlUivb/ltQt8AcPEsF8uiBiKr2HI4sCv/sgjMIawYqhNTh6rrekaUIMj64dvQRir2kEm78WONy2Yjmy2S1nef+Z/sNXrTTU0TDHiWo+uDIg+haclSwc/8yOzVAD6t1dL4sFaNpPADh2NiTOJc5y4x1mT3HPPaC33UyHpvL3rJXMJgIGBWWEm38ILMwAeROzotKUxFkNNS0q/czG4FDoyOA5Ej+3V1m722pcTzUqgzmWzy00C2hfaD1DxDnmuZe4ZhJsvXhaKm2Iaj8c4kyeyeC0n7Y7cRM38amokJtlr71thgsz5fURtLvYTBLOjqF3qekEpDQ0wiZ62efETFNKe0bww1o7pW2Qs6S0usND8vibQWZSjR5r0adEbK6rPCNFdj139E0kSwTyqht7fQs/saT4DRHcuknY5mWBd3zhGi6JL0sJ4="
