sudo: required
services:
- docker
before_install:
- docker pull davidski/evaluator-docker:latest
install:
- docker build --cache-from davidski/evaluator-docker:latest -t davidski/evaluator-docker
  .
- docker run -d --name evaluator evaluator-docker
script:
- docker ps |grep -q rstudio
after_success:
- docker rm -f evaluator
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push davidski/evaluator-docker:latest
notifications:
  slack:
    secure: lBu+n1YP9FaPTiSpDWZqBXDJF1yoTC77kw6VI26S0GO8RcyEMZZNYGsjiEoTu1SMxbJsvIRC6Jg3kiU7Vnoz9lV/Oj9Xp8oEmS5gL3AGiXq6L7yDxshOjAK0coa+aKIp6aP7xjOVZ9DqI7hCIJnelz9j/1APEwuPC+av4kBtcvnnz4oClKDn+LRpowIGJufZ1IplCXjIyb89WOvjwI7hA/0WO8m6B/W1vU9xxQfeVeaeCRc/29RrIIX1elXLdu1YF8q56DJsnspNSFP8RuXMXvID5IXIXFqfOKb6G5BhYjNvaeovP2MCd5XpO7LYWQzAttRRoKLYO+f3MFRNb4iLIcciGcGa6h/pus7YQud/dWfj94zFleWp0xezduFLgJFrQd8BQXQiSjPcWTA+okwQqCf9DEFJMgCcC1i5vEE2OYtExicG5+835v+n38MrQdRp144Xl0X+bqITWb2xjfCDk5SHdAXR9poNPp5356Pj1roptbO9byZX1afoxEZ1CF3T5F+H7PQjuFWq6P+uDQpOS6+0hVtRrU6ry6MmXUnfmcAA+kqlNmdVDE8VTyckIzxzg9Ac3X94uaNZrUxarPOIGOQhP0Gj+wrtc3wx/BdLspJMtLS/PHq560UiUU/glbGllEClBQl+sCqRs9hsJwC8znlXvSAy28bf4oHhiGyiqD8=
env:
  global:
  - secure: Rks7BuPVU1O9LDfn8GoaWuXSwfz4ywV+EVXhkiOnUXEpicyxepW7oXFa7EceBa/k/CybD3H729BOhqxpoWHJ6GkSgkj4k2noYfvciemJD65/gxHk6RsmrmALIHvCLmkSDaJDXQdWN1vtmwWTGScTBwf3RZe8qWQkKVMI0RBHR4VypWLP+fylaLHsD3YrMBeOJD56xqTMZU4O1w8a6AheprWy44zDmq1H6JmDu388PdF8nA+sIfCIow1b/NgyyssPaF0h/Xw7TJ/YjufXtlKMHl59nV+UfPZyJoV61Q04FONoWVt9ZNmTUwt1tf2KxTLQz/k9Wc5MPqsWEVGaAADhlKHQiUAXf4t4B9WNVmnHODIMDzfcxTEbn3xlTASYxjYkA8ydM/l+A1uoIx74M5tZofU0v7durXGPFDtram1IT+e7Do2Xa6RbEHNBzvwax/qxwTicr+cNS8gIXe78238w05vdQH9x3YhNOPatPAnrhx/uiWcL59RQ593wCqcQNjUfavfvZUtjCRdvImhnq5lB6gxFAHUWZD9BN8+j6Gmlzgfn/D0+6J2/koWepTCqprt0UdtiUeKyDp2EthO5uY/v8a0npgdGQ409NZ7f4/zOFzoxanaSx75DtvfbZj+Sy8FmM0//pNFT/gC0iw8sdWGWS/z348l3raHiILNpN6MhpGQ=
  - secure: TivdXbHA+DBFL+V5xYcQuw57s9Gpg5MskxO1rpxs/YNtnbxUXEZUIXvGY1VZ4sMpGIbcoXwZbypYSJxbU8H9F/FxUlWEMcDP6bL3yR16+SQZcsPNxe/RLIS/j6rYHFNvPzjLE2EVvGOxZnF5Bg9f2FV2GdmckJ5RX+EVz9n9odd7ferMGxbT7y7RpNz7RdxxUen/LSMNgKWnMtswsflKDK7Ux9zRoBNfhnmjlon8c2x989LV0SywLo2sbotyrwy7SknV0VJIyWq0qw55H8uihR70Mud6Z6zrdIX7Hl1z38d6W4v8wpFXvqcj4eqLqLkRwsoOTdqdTyw+WMT58GjrXCxEnyJB0mymAxcyuJjZWF7JuSFKh5VpMrejdHinCivAat53r0FIqsXtfP2KdIWxEDc/wLkRxUCAjY87WzU/iI2Q+xVot7NcWhfr+jQiqYQcEYpnhfUMawB6QV1vBYYQWgry7z+WwzfN07FRodp5KbfLmL4sZvuHfIAeE51nPPHkvnfspD0p6Mk+kVTRSXaPMCECDGY6TicGJ4muO9DU9uMmIgI7FE1HCTRKn+ErhMyP4d892WRD0LBVPxmqlqqxHux7t5IrSwGRDCTsWa3CtUaWlE1k2V9DUZPl0uSruxL+MQpktv3/7UJIgrxhr0/6dt7cm2VSgIIChHWncJIbb+o=
